/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: seangorman (https://sketchfab.com/seangorman)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zombie-pickup-truck-23708528454e43b58e02d78fd427c240
Title: ZOMBIE PICKUP TRUCK
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials['03_-_Default']} position={[-0.014, 35.851, -7.895]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['02-_Default']} position={[0, 80.502, -6.549]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['13_-_Default']} position={[68.124, 138.651, -34.101]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
